/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_796726_5_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_796726_1[] = { "knock", "noise" };

ei_dsp_named_axis_t ei_dsp_config_796726_2_named_axes[] = {
    { .name = "Signal", .axis = 0 }
};
size_t ei_dsp_config_796726_2_named_axes_size = 1;
EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_796726_2_axes[] = { 0 };
const uint32_t ei_dsp_config_796726_2_axes_size = 1;
ei_dsp_config_spectrogram_t ei_dsp_config_796726_2 = {
    2, // uint32_t blockId
    4, // int implementationVersion
    1, // int length of axes
    ei_dsp_config_796726_2_named_axes, // named axes
    ei_dsp_config_796726_2_named_axes_size, // size of the named axes array
    0.064f, // float frame_length
    0.048f, // float frame_stride
    32, // int fft_length
    -131, // int noise_floor_db
    true // boolean show_axes
};

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_796726_6_axes[] = { 0 };
const uint32_t ei_dsp_config_796726_6_axes_size = 1;
ei_dsp_config_spectral_analysis_t ei_dsp_config_796726_6 = {
    6, // uint32_t blockId
    4, // int implementationVersion
    1, // int length of axes
    0.04581061790877f, // float scale-axes
    1, // int input-decimation-ratio
    "low", // select filter-type
    167.96875f, // float filter-cutoff
    6, // int filter-order
    "Wavelet", // select analysis-type
    4096, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    false, // boolean do-fft-overlap
    2, // int wavelet-level
    "bior1.5", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_796726_6[42] = { 1.43542849533845, 0.1926781508427952, 0.08329003674821704, -0.009510485746622567, -0.003196634277409578, 0.0016159937360536683, 0.022048844023319986, -0.00132098827462388, -0.005749921531401848, 0.051521942799628094, 0.0028582340745128576, 0.051851198233234946, -4.312698039396895, 28.12893947381624, 1.0215750380336301, 0.5899444450258584, 0.49726230311768216, -0.005486212516598482, -0.000613609467832986, 0.0006738817710880464, 0.006482828897606894, -0.000003338794658464594, -0.0001869994836794988, 0.06750335517041971, 0.004594537973189385, 0.06750578905275355, 0.0043251993756616945, 28.754705788577414, 1.1088849870946396, 0.5852537414166316, 0.5714845209533631, -0.002546367327516889, -0.00030453856057714165, 0.0002744573900471222, 0.0024819448818842738, -0.000010989622606133832, -0.00005307394281457573, 0.014442084791109512, 0.00021046833328705242, 0.014442183798988453, 0.009156415326745097, 97.29456281412334 };
const float ei_dn_standard_scaler_scale_796726_6[42] = { 1.7685944753452738, 7.355997070125375, 10.250101599461194, 81.69856523554145, 166.92326990026805, 271.36633555780134, 41.707513920400004, 193.24999390567208, 3261.67755191495, 74.14430547927238, 470.8217528354731, 74.32440763918846, 0.38925106476949606, 0.20790902571791892, 4.4958244688202855, 18.237510366489047, 9.95971797456385, 138.91534305948628, 3172.016957973165, 2257.185134723734, 113.93617100068566, 12958.804561195879, 1793.104936466084, 601.6873180558005, 4251.040798278, 599.799863129957, 19.317663776089788, 0.4541914289201424, 4.5158313372208, 18.190735103366304, 18.91354148520741, 413.0180551553532, 5310.894954229991, 5997.0425042876295, 350.93942686869406, 44516.64036812673, 190225.6495410322, 968.59240602999, 30242.689249783678, 968.5982555482994, 9.473548532489962, 0.05969734407175053 };
const float ei_dn_standard_scaler_var_796726_6[42] = { 0.31970061513418974, 0.018480635646777946, 0.009517955274333247, 0.00014982046500814104, 0.00003588940288477096, 0.00001357963383813042, 0.0005748723136636269, 0.00002677694473264289, 9.399785660911888e-8, 0.00018190489968720775, 0.000004511146803560989, 0.00018102438754469434, 6.599945990004423, 23.134137549496327, 0.04947448779292461, 0.0030065532244050786, 0.010081053471104603, 0.00005182025770811712, 9.938686669961417e-8, 1.962752942450664e-7, 0.00007703299078054051, 5.954840313649569e-9, 3.1102019379514477e-7, 0.000002762220119954722, 5.5336215498138136e-8, 0.0000027796318245510575, 0.0026797284939472955, 4.847548146955062, 0.04903707690221467, 0.0030220350756679087, 0.0027954664683695197, 0.000005862217469568659, 3.545394585161947e-8, 2.7805182257829823e-8, 0.000008119619446370039, 5.046092854804567e-10, 2.7635151423045398e-11, 0.0000010659034808897507, 1.0933499413067478e-9, 0.0000010658906066086654, 0.011142294456667883, 280.60149484402126 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_796726_6 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_796726_6,
    .mean_data_len = 42,
    .scale_data = (float *)ei_dn_standard_scaler_scale_796726_6,
    .scale_data_len = 42,
    .var_data = (float *)ei_dn_standard_scaler_var_796726_6,
    .var_data_len = 42
};
ei_data_normalization_t ei_data_normalization_config_796726_6 = {
    (void *) &ei_data_normalization_standard_scaler_config_796726_6, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_796726_1_size = 2;
ei_model_dsp_t ei_dsp_blocks_796726_1[ei_dsp_blocks_796726_1_size] = {
    { // DSP block 2
        2,
        340, // output size
        &extract_spectrogram_features, // DSP function pointer
        (void*)&ei_dsp_config_796726_2, // pointer to config struct
        ei_dsp_config_796726_2_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_796726_2_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        nullptr, // data normalization config
    },
    { // DSP block 6
        6,
        42, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_796726_6, // pointer to config struct
        ei_dsp_config_796726_6_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_796726_6_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_796726_6, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_796726_5 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_796726_5_init,
    .model_invoke = &tflite_learn_796726_5_invoke,
    .model_reset = &tflite_learn_796726_5_reset,
    .model_input = &tflite_learn_796726_5_input,
    .model_output = &tflite_learn_796726_5_output,
};

const uint8_t ei_output_tensors_indices_796726_5[1] = { 0 };
const uint8_t ei_output_tensors_size_796726_5 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_796726_5 = {
    .implementation_version = 1,
    .block_id = 5,
    .output_tensors_indices = ei_output_tensors_indices_796726_5,
    .output_tensors_size = ei_output_tensors_size_796726_5,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_796726_5,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_796726_1_size = 1;
const uint32_t ei_learning_block_796726_5_inputs[2] = { 2,6 };
const uint8_t ei_learning_block_796726_5_inputs_size = 2;
const ei_learning_block_t ei_learning_blocks_796726_1[ei_learning_blocks_796726_1_size] = {
    {
        5,
        &run_nn_inference,
        (void*)&ei_learning_block_config_796726_5,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_796726_5_inputs,
        ei_learning_block_796726_5_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_796726_5 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_796726_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_796726_1[ei_postprocessing_blocks_796726_1_size] = {
    {
        .block_id = 5,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_796726_5,
        .input_block_id = 5
    },
};

const uint8_t freeform_outputs_796726_1_size = 0;

uint32_t *freeform_outputs_796726_1 = nullptr;

const ei_impulse_t impulse_796726_1 = {
    .project_id = 796726,
    .project_owner = "darrelzhao06",
    .project_name = "knock-detector-ml",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 5,

    .nn_input_frame_size = 382,
    .raw_sample_count = 500,
    .raw_samples_per_frame = 1,
    .dsp_input_frame_size = 500 * 1,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 2,
    .frequency = 500,

    .dsp_blocks_size = ei_dsp_blocks_796726_1_size,
    .dsp_blocks = ei_dsp_blocks_796726_1,

    .learning_blocks_size = ei_learning_blocks_796726_1_size,
    .learning_blocks = ei_learning_blocks_796726_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_796726_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_796726_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "imu",
    .slice_size = (500/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 2,
    .categories = ei_classifier_inferencing_categories_796726_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_796726_1_size,
    .freeform_outputs = freeform_outputs_796726_1
};

ei_impulse_handle_t impulse_handle_796726_1 = ei_impulse_handle_t( &impulse_796726_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_796726_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_796726_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_796726_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_796726_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
