/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_796726_5_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_796726_1[] = { "knock", "noise" };

ei_dsp_named_axis_t ei_dsp_config_796726_2_named_axes[] = {
    { .name = "Signal", .axis = 0 }
};
size_t ei_dsp_config_796726_2_named_axes_size = 1;
EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_796726_2_axes[] = { 0 };
const uint32_t ei_dsp_config_796726_2_axes_size = 1;
ei_dsp_config_spectrogram_t ei_dsp_config_796726_2 = {
    2, // uint32_t blockId
    4, // int implementationVersion
    1, // int length of axes
    ei_dsp_config_796726_2_named_axes, // named axes
    ei_dsp_config_796726_2_named_axes_size, // size of the named axes array
    0.32f, // float frame_length
    0.64f, // float frame_stride
    32, // int fft_length
    -131, // int noise_floor_db
    true // boolean show_axes
};

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_796726_3_axes[] = { 0 };
const uint32_t ei_dsp_config_796726_3_axes_size = 1;
ei_dsp_config_spectral_analysis_t ei_dsp_config_796726_3 = {
    3, // uint32_t blockId
    4, // int implementationVersion
    1, // int length of axes
    0.07510545875759f, // float scale-axes
    1, // int input-decimation-ratio
    "low", // select filter-type
    41.015625f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    128, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    false, // boolean do-fft-overlap
    1, // int wavelet-level
    "rbio3.3", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_796726_3[58] = { 0.053183582714862294, -7.687302695380317, 69.21117697821722, 0.8202762694822417, -0.2811843170267012, -2.6234838167826333, -2.869729128148821, -2.9177281260490417, -2.8476249045795865, -2.9762852523061962, -2.838997417026096, -2.8651378750801086, -2.91140572892295, -2.8285311261812844, -2.912898381551107, -2.7953005168173046, -2.8445970482296414, -2.871034628815121, -2.791078805923462, -2.8754135502709284, -2.772256334622701, -2.797931128078037, -2.808552039994134, -2.750161237186856, -2.82832803328832, -2.762837549050649, -2.7414140833748712, -2.766329672601488, -2.7102729148334928, -2.745829224586487, -2.7150756186909146, -2.6744055681758456, -2.7164894541104636, -2.6351808640691967, -2.662820471657647, -2.637966619597541, -2.5825405518213906, -2.635350955857171, -2.541820181740655, -2.619187739160326, -2.524397975868649, -2.509867787361145, -2.518070148097144, -2.4583176838027105, -2.4917475250032215, -2.415864090124766, -2.41690993309021, -2.3978432019551597, -2.366555823220147, -2.3495591349071927, -2.3394653068648443, -2.3099523186683655, -2.3316446012920804, -2.3127458691596985, -2.366556074884203, -2.4344106449021234, -2.627992676364051, -2.9403355717658997 };
const float ei_dn_standard_scaler_scale_796726_3[58] = { 575.7066055055603, 1.4084926613095372, 0.15295670655383398, 6.381085882286003, 4.136736457757194, 6.199227746905072, 9.251139275881947, 7.495997680563701, 6.350729956682182, 2.4176147921965465, 5.81150928466229, 7.237990898976611, 6.552696376322425, 6.804459557505374, 3.434571556438292, 8.906393084386409, 9.24095158264658, 8.459992725679419, 5.867690642536636, 4.504672278059929, 8.029040740615462, 11.6589712148496, 10.597954942050004, 7.695028925658828, 4.860616307596462, 9.843477559524013, 17.387536944967813, 12.747125747815435, 10.968432587466177, 9.027506888403662, 15.599681905781951, 17.104082387265517, 8.36543920287817, 10.706019341602685, 16.472811954162868, 13.455536373349194, 9.250601401783454, 7.726526031544129, 8.535404920689025, 5.539055582621696, 13.876629832857295, 32.68605801519588, 18.81525565853358, 12.778998715225514, 10.151591629579485, 19.47764209803386, 20.503045428803798, 28.197265039388476, 28.19490293246885, 34.84437352328637, 33.321845585856174, 27.93525564733199, 22.132100416345, 22.075493850909353, 21.037769586168384, 28.49025680541004, 43.83637415568541, 42.10290169817605 };
const float ei_dn_standard_scaler_var_796726_3[58] = { 0.0000030171546759617743, 0.5040699675380705, 42.7427983979191, 0.02455900799213045, 0.058436512908405604, 0.02602104995974565, 0.011684484623297929, 0.01779676693536953, 0.024794348862809193, 0.17109045903826087, 0.029608890101669023, 0.019088154196056212, 0.02328948632596551, 0.02159795965832995, 0.08477247483266596, 0.012606550919208512, 0.011710261960322413, 0.01397204644998512, 0.029044612210125505, 0.049280328968050596, 0.015512174329433356, 0.007356640604451901, 0.008903399534400556, 0.016888049242584875, 0.04232698367925794, 0.010320551109200849, 0.0033076829027939873, 0.00615425461340565, 0.008312101909734432, 0.012270558860031934, 0.00410930630570914, 0.0034182233806489665, 0.014289680068563607, 0.008724568417449544, 0.003685229325922658, 0.005523291582410949, 0.011685843446162244, 0.01675064195754615, 0.013726244867151296, 0.032593316480871146, 0.005193163466734649, 0.0009359979672893814, 0.0028247482767205945, 0.006123593410575961, 0.00970357399753879, 0.002635889725131414, 0.0023788291521466614, 0.0012577259658207319, 0.0012579367136754773, 0.0008236347824038498, 0.0009006206591942585, 0.0012814294469206307, 0.0020415251572343807, 0.002052008446438849, 0.0022594389517023943, 0.001231990253901672, 0.0005203921656933751, 0.0005641257758396042 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_796726_3 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_796726_3,
    .mean_data_len = 58,
    .scale_data = (float *)ei_dn_standard_scaler_scale_796726_3,
    .scale_data_len = 58,
    .var_data = (float *)ei_dn_standard_scaler_var_796726_3,
    .var_data_len = 58
};
ei_data_normalization_t ei_data_normalization_config_796726_3 = {
    (void *) &ei_data_normalization_standard_scaler_config_796726_3, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_796726_1_size = 2;
ei_model_dsp_t ei_dsp_blocks_796726_1[ei_dsp_blocks_796726_1_size] = {
    { // DSP block 2
        2,
        34, // output size
        &extract_spectrogram_features, // DSP function pointer
        (void*)&ei_dsp_config_796726_2, // pointer to config struct
        ei_dsp_config_796726_2_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_796726_2_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        nullptr, // data normalization config
    },
    { // DSP block 3
        3,
        58, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_796726_3, // pointer to config struct
        ei_dsp_config_796726_3_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_796726_3_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_796726_3, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_796726_5 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_796726_5_init,
    .model_invoke = &tflite_learn_796726_5_invoke,
    .model_reset = &tflite_learn_796726_5_reset,
    .model_input = &tflite_learn_796726_5_input,
    .model_output = &tflite_learn_796726_5_output,
};

const uint8_t ei_output_tensors_indices_796726_5[1] = { 0 };
const uint8_t ei_output_tensors_size_796726_5 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_796726_5 = {
    .implementation_version = 1,
    .block_id = 5,
    .output_tensors_indices = ei_output_tensors_indices_796726_5,
    .output_tensors_size = ei_output_tensors_size_796726_5,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_796726_5,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_796726_1_size = 1;
const uint32_t ei_learning_block_796726_5_inputs[2] = { 2,3 };
const uint8_t ei_learning_block_796726_5_inputs_size = 2;
const ei_learning_block_t ei_learning_blocks_796726_1[ei_learning_blocks_796726_1_size] = {
    {
        5,
        &run_nn_inference,
        (void*)&ei_learning_block_config_796726_5,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_796726_5_inputs,
        ei_learning_block_796726_5_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_796726_5 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_796726_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_796726_1[ei_postprocessing_blocks_796726_1_size] = {
    {
        .block_id = 5,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_796726_5,
        .input_block_id = 5
    },
};

const uint8_t freeform_outputs_796726_1_size = 0;

uint32_t *freeform_outputs_796726_1 = nullptr;

const ei_impulse_t impulse_796726_1 = {
    .project_id = 796726,
    .project_owner = "darrelzhao06",
    .project_name = "knock-detector-ml",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 3,

    .nn_input_frame_size = 92,
    .raw_sample_count = 100,
    .raw_samples_per_frame = 1,
    .dsp_input_frame_size = 100 * 1,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 10,
    .frequency = 100,

    .dsp_blocks_size = ei_dsp_blocks_796726_1_size,
    .dsp_blocks = ei_dsp_blocks_796726_1,

    .learning_blocks_size = ei_learning_blocks_796726_1_size,
    .learning_blocks = ei_learning_blocks_796726_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_796726_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_796726_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "imu",
    .slice_size = (100/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 2,
    .categories = ei_classifier_inferencing_categories_796726_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_796726_1_size,
    .freeform_outputs = freeform_outputs_796726_1
};

ei_impulse_handle_t impulse_handle_796726_1 = ei_impulse_handle_t( &impulse_796726_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_796726_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_796726_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_796726_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_796726_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
