/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 09.12.2025 20:18:05

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1456;
#else
constexpr int kTensorArenaSize = 432;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,92 } };
const TfArray<1, float> quant0_scale = { 1, { 0.038451638072729111, } };
const TfArray<1, int> quant0_zero = { 1, { 5 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[2] = { 53, -53, };
const TfArray<1, int> tensor_dimension1 = { 1, { 2 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00015222953516058624, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[2*10] = { 
  73, -107, 77, 107, 127, -79, -46, -110, 8, 90, 
  73, 17, -26, -22, -99, -2, -119, 57, -95, 37, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 2,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0054629682563245296, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { -87, 133, 141, 79, 144, -105, -110, -53, 76, 78, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.0001079692374332808, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  41, -85, -75, 12, 105, 14, 119, -109, -9, -51, 23, 17, 65, 119, 60, -91, 2, -31, -76, 22, 
  -59, -118, 77, 76, 62, -40, -53, -102, -96, 18, -52, -54, 71, 28, 77, 100, -50, 41, -47, -29, 
  -22, -100, 0, 117, -48, -62, -35, 26, -40, -8, 35, 59, -23, -93, -10, -75, 93, -101, -107, -84, 
  65, 17, 102, -1, -75, 79, -66, -45, -30, 83, 103, 56, -83, -105, -2, -53, -32, -61, 113, 86, 
  -47, 68, -105, -49, -94, 73, -36, 33, -96, 70, 94, 65, -25, 53, 31, -101, -49, 105, 78, 65, 
  -93, 72, -77, 56, -34, -122, -10, 80, -127, -55, 87, 61, -51, 67, -30, -70, -43, 70, -73, 1, 
  97, 54, -67, -88, 83, 81, 15, -32, -32, 7, 64, 48, -80, -47, 14, -22, 68, -22, -17, -34, 
  -18, 95, 49, 68, -8, 96, 94, -122, 124, -37, -59, 118, 75, -25, -110, 58, 89, 9, 14, 92, 
  69, 46, 60, 42, 90, 33, -118, -24, -32, 18, 98, 27, -9, -117, -33, 98, -92, 73, -51, -39, 
  48, -74, -15, -3, 84, 105, -22, 15, 80, -95, -68, 56, -84, -62, 64, -24, -16, 92, 3, 80, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0035663212183862925, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { -7, -123, 101, -153, -37, -170, -115, 54, -141, 194, -145, -17, 195, 186, 173, 172, -158, -140, 0, -81, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 7.4421135650482029e-05, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*92] = { 
  -1, -18, -28, 96, 33, 56, 34, -75, 40, -94, -6, 42, -104, -76, -25, 104, 30, 85, -60, -60, 99, -34, 97, 20, -110, 74, -58, -58, -83, -107, 27, 34, 69, -99, -117, 44, -67, 92, -4, -83, 47, -3, -95, -34, -94, 89, -34, 97, -71, -91, -28, -103, 40, -19, -103, 68, 118, 81, 120, 71, 38, -41, 6, -89, -11, -89, 8, 31, 106, -9, 21, -94, -65, -38, -18, -71, 88, 52, -23, 104, 32, 2, -27, 42, -17, 8, -116, -7, -96, -109, 47, -35, 
  -120, -12, 92, 10, -39, 15, 32, 31, 47, 104, -80, 45, 11, 17, 68, -68, 87, 53, 115, -74, -24, -16, 92, -27, 55, 52, -26, 80, -33, -91, -23, 106, 97, 109, 86, -32, -99, -17, 25, -46, -43, -72, 120, 79, 60, -23, 80, -79, 5, 6, -102, -19, 8, -48, -11, -118, -117, 99, 95, -93, -18, 79, -47, -26, -24, 7, 83, -112, 64, -37, 110, -70, 75, -13, 21, 95, -31, -72, -7, 112, -21, -113, -55, -1, 53, 13, -29, -81, 19, -24, 31, 43, 
  80, -12, -97, -80, 55, -58, 76, 103, 116, -6, -85, 23, -82, 61, -65, 86, 41, 73, 5, 54, 121, -106, 69, -89, 18, -26, 117, 63, -57, -88, -56, 81, 64, -81, -23, -40, -99, -13, 62, -89, 63, 69, -103, -27, 50, -31, -60, -88, 35, -26, 56, -31, -15, -9, 61, -92, 10, 11, 14, -36, 114, -47, -12, 21, -36, 74, 18, -60, -42, -45, 0, -122, 4, 105, -22, -108, -94, 59, -52, -78, 44, -62, 48, -11, 7, 26, -37, -1, -101, 7, -89, 92, 
  -104, 57, -68, 64, -15, 63, -18, 108, 53, -106, 91, 89, 52, 67, 45, -32, -96, -63, 35, 70, -83, 44, -82, -50, 66, 54, -90, 64, 93, 71, -58, 43, 93, -58, 78, 22, 108, -120, 16, 88, -105, 67, 9, 84, 120, -84, -12, -68, 63, 61, -70, -11, -16, -126, 35, -84, -109, -108, -55, -20, 113, 33, 119, 92, -86, -99, 60, -95, -81, -115, 75, -69, -71, -77, 18, 34, -24, 112, 49, 108, 17, 68, 89, -43, -30, -88, -16, -51, 80, -43, 46, 47, 
  95, 23, 18, -74, -94, -87, 99, -29, -59, 67, -35, 21, -75, -53, -84, 61, 63, 76, -11, -29, -13, 108, -24, -20, -39, 5, 85, 80, -109, -95, 53, -81, 105, -88, -41, -62, -33, -107, 29, 71, 4, 41, -102, -39, 61, -77, 88, 68, -17, 76, 69, 92, -97, -25, -37, 114, 74, 84, 108, 64, -97, -99, 105, 114, 1, 63, -45, 112, -111, -34, -97, 25, 77, 45, 43, 53, -37, -37, -52, -54, 85, -119, 64, -90, 44, -68, 29, -88, 82, -45, -50, 2, 
  -42, 82, 14, -12, -46, -100, 5, 111, -52, 19, -117, -49, -123, 49, 14, -8, -113, 27, -43, 3, -99, -104, -18, -66, 80, -37, 26, -23, -63, 110, -30, -19, 85, -79, 21, -117, 87, -62, 55, 97, 74, 52, -88, -26, 14, -123, -82, -86, 3, 69, 97, -10, 32, -41, 46, 64, 47, -21, 72, 11, 24, -106, 71, -100, -26, -7, -37, 87, 108, 60, 104, -47, 87, -94, -111, -83, -7, -11, 69, 7, -91, 50, -65, 100, -3, -97, 41, -1, 110, -14, 10, 1, 
  53, -37, -46, -69, -77, -120, -43, 80, -46, 6, -9, -13, -3, 65, 42, -23, -51, -65, 112, 87, -61, 18, -58, 72, -52, -16, 114, -103, 91, 26, 75, -114, -3, -19, -87, 74, -112, 43, -102, 126, -7, 18, -4, 0, -54, -107, 108, -58, -17, -20, -82, 94, -98, 68, 43, -8, 17, 102, 60, -44, -68, 7, 88, -76, 58, 37, -112, 81, -93, -71, 25, 99, -30, 51, 39, 64, 62, 87, 58, -45, 82, 79, 11, 29, -61, -30, 69, 35, -61, -44, -90, 77, 
  89, -118, 33, 101, 102, 35, 33, 49, -36, 100, -27, 114, -41, 47, -76, -113, -38, -61, -81, 109, 99, -75, -61, -1, -25, 116, -30, 34, -110, -17, 28, 109, 27, -103, -49, -117, -14, 38, 86, -40, -17, 41, 112, 119, 49, -20, 32, -94, -78, 50, -87, -28, -14, 17, -42, -67, -109, 86, 81, -112, -83, -46, 60, -94, 56, 25, 34, -55, -52, 125, -77, 23, -17, 41, -6, 26, -49, 72, -68, 64, 122, -122, 62, -1, 23, -114, 41, 46, 80, -47, -38, -101, 
  59, 110, 71, -24, -105, 69, -20, -76, -16, -25, 6, 67, 63, -49, 13, -56, 43, -60, 120, 28, 107, 81, 100, 43, 68, 70, 79, -17, 93, -108, 61, -115, -22, -6, -91, -27, -110, 93, -85, 18, -61, -69, -101, -51, -112, 42, -48, -9, -65, 42, -103, -121, 123, -80, 67, 62, 10, 61, -19, -36, 80, -32, 106, -45, 1, -107, 96, 91, 69, -66, -45, -39, 14, -90, -42, -104, -88, -51, -62, 93, -56, -76, -86, -60, 96, 31, -11, 38, 75, 63, -7, -100, 
  -92, 61, -93, 0, -61, 78, -101, 7, -57, -112, -94, -74, -112, -23, -68, 100, -5, 77, 91, -68, -17, 82, 31, 118, 127, 88, 14, 43, 4, 61, -45, -26, -79, 4, 76, 29, 88, 97, -9, 9, 35, 58, -72, 36, -49, -127, 84, 41, 109, -100, 53, 120, -121, -104, -78, 15, 62, 6, -100, 30, -112, -58, -90, 97, -6, -35, -104, -41, -77, 52, -81, 85, 95, 10, -29, -87, 108, -34, -119, 81, 64, 113, -109, -62, -88, 83, -73, -71, 63, 15, 101, 38, 
  108, 22, 48, -119, -99, -53, 64, 14, -13, 34, -96, 30, 26, -98, 51, -74, -7, -7, 36, 20, -107, 49, -115, 87, 92, -27, -62, -43, 79, 75, -120, -100, -100, -31, 111, 98, -27, -86, -86, 26, 39, -16, -1, -30, -36, 76, 14, -120, 77, 39, -44, -67, -30, -1, 78, 97, -71, -57, 33, -13, 24, 47, 69, 73, 37, -122, -100, 46, 61, 40, 85, 20, -20, -55, 5, 100, 40, -83, 47, 125, -44, -75, 29, -73, -44, 73, -34, 38, -52, -54, -8, 104, 
  -17, 40, 105, -37, -91, -107, 117, -47, 87, -28, 101, 109, 75, 107, -44, 53, -49, -42, 107, 3, -27, -26, 113, 4, 36, 46, 74, 57, 119, 45, -11, -25, 4, -49, 34, -25, -84, 27, 28, 70, 58, 78, 105, -20, -65, -33, 21, 57, -106, -9, -87, 75, 38, 38, 108, 67, 53, -17, 13, -99, 94, 63, -3, -37, 90, 75, 73, -27, -26, -26, -90, 2, -64, -73, 99, 30, 55, 91, 55, 26, 48, 113, -101, -60, -119, -105, -76, 57, -17, 77, 66, -94, 
  -47, -106, 9, -30, 79, -95, -63, -108, -88, 64, -20, -102, 37, 71, -34, 95, 23, -33, 106, -25, 63, 74, -67, 81, 67, -30, 16, -50, 107, -24, -43, 36, -107, 114, 78, 78, 91, -85, -107, -67, -19, 26, -99, -55, -120, -50, 115, 71, -23, 124, 85, -110, -115, 17, -74, -114, -72, 36, -26, 55, -38, -88, -87, 76, 25, 35, 73, 49, 6, 84, 4, -60, 58, 73, 38, -125, -45, 91, -97, -107, 20, 49, 108, 78, 106, 94, -111, -65, -1, 80, -85, 115, 
  35, -112, -58, 1, 113, 122, -93, 118, -9, 35, 30, 39, 112, 39, -16, -77, -112, -12, -89, -37, -84, -87, 1, -32, -44, -112, -73, 109, -12, 16, 43, -108, -81, -108, -12, 35, 47, -15, 90, -45, 117, 65, 101, -92, 101, -66, -13, 59, 121, 79, 44, 48, -90, -62, 112, -54, 28, 88, 54, -17, 7, -32, -16, -85, 84, 97, 92, 99, 18, 118, -95, -22, 79, -24, 61, -94, -70, -52, 64, -74, -42, 56, -27, -34, 61, 25, 87, 107, -10, -110, 15, 33, 
  114, -94, -58, 29, 14, -64, -47, 47, 62, 46, 121, -111, -95, 121, -110, -39, -99, 22, 73, -88, 106, 121, -54, 92, -105, -64, -11, -91, 99, -27, 126, -58, -48, 79, -26, -86, -88, 34, 101, -118, -114, 104, -121, 82, -11, 64, -37, -79, -110, -58, -31, 57, 36, -15, -97, -69, 99, -37, 109, -75, 2, 53, -78, 114, 13, 99, 108, 66, -19, 68, 5, -67, 100, -42, 94, 62, -56, 36, -10, 8, 68, 8, -88, -49, 14, -102, 95, 3, -93, 16, -46, 28, 
  7, 107, -81, -105, -104, 39, -8, 26, 50, 46, 0, 52, -60, 62, 63, 99, 26, 59, 48, 77, -102, 106, -90, 59, 34, 7, -46, -37, -16, -59, 38, -35, -36, 69, -2, 32, -7, -117, 23, 111, 75, -52, 42, -92, 89, -67, -114, -23, -93, 89, 56, -17, 90, 94, 53, -61, 97, 59, -90, 93, 10, -80, 29, -44, 12, 55, 12, -64, 4, 69, -95, 90, 89, 109, 42, 78, -44, 21, 107, 37, -89, -63, 22, 105, 112, 98, 5, 57, 71, 124, 3, 125, 
  -4, -82, -53, -15, 90, -34, -46, -92, 37, -111, -110, -44, 21, 52, -47, 37, -100, -65, 45, -44, -106, -75, 39, -57, 43, -45, -27, 85, -89, 79, 37, -7, 86, -77, -29, -56, 28, -108, -59, 8, 6, -25, 27, 80, -7, -102, 87, -103, -15, -41, 3, -8, -18, -83, -10, -118, -12, -31, 83, -89, -71, 96, -63, 3, -90, 60, -4, -39, -8, 106, -92, -30, -54, 106, 95, 56, -50, 26, -65, 18, 20, 111, -113, -45, -2, 85, 0, -67, 106, -23, 8, 110, 
  -28, 53, 100, 78, 81, -42, -52, 94, 36, -21, -47, 110, -47, 79, -90, -45, -88, 26, 104, -70, 58, -56, -93, 111, -69, -97, -65, 33, -14, -74, -21, -95, -1, 24, 6, 113, 117, -59, 88, -104, -115, -34, 115, -33, 30, -81, 14, 109, -86, 53, -59, -64, 105, 67, 31, -93, 93, -108, -31, -52, 31, -88, 53, 107, -20, 58, -9, -1, 41, -29, 87, -39, 80, 103, 60, 25, -91, -84, 82, -84, -92, -103, -109, 25, 66, 106, -51, 32, 22, 57, -7, 110, 
  -100, -30, 63, -116, 57, 10, -77, -11, -3, -42, -110, -45, -102, -84, -89, -62, 8, -70, -65, 46, -59, 98, -65, 93, -52, -104, -5, -34, -106, -82, 55, -51, -75, -107, 117, 94, 33, -80, -92, -40, -86, 24, -71, 61, 3, -19, 119, 27, -94, -109, 7, -101, 53, -68, 75, -84, -77, -75, -33, 85, -37, -62, -78, 93, 59, -62, 104, -96, 6, 104, 74, 65, 90, -54, -112, 36, 106, 21, -35, 41, 34, 50, 103, -3, 57, 21, 101, 12, -6, -95, -113, 94, 
  -7, 86, 3, -61, -23, -42, 32, -19, 82, 78, -100, 91, 78, -4, -5, -52, -6, -103, -66, 29, -48, -112, 91, -96, -11, 0, -80, -53, 39, 91, -86, 15, 97, -76, 13, 44, -112, 29, 11, -13, -72, -89, 37, 63, -3, -90, -118, 34, -15, 5, 34, 49, -99, 38, 57, -62, 55, -92, -83, 102, -91, 80, -89, 37, -86, -10, -23, -78, -85, -70, -115, 81, -33, -22, -21, 40, -99, -112, -110, -47, 91, -7, -9, -97, -31, 44, 101, -13, 33, 2, -116, 25, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,92 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0019354476826265454, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.030274681746959686, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.027865719050168991, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,2 } };
const TfArray<1, float> quant9_scale = { 1, { 0.021850626915693283, } };
const TfArray<1, int> quant9_zero = { 1, { 95 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 92, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1840, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 96), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_796726_5_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_796726_5_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_796726_5_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_796726_5_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_796726_5_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
